repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint app/ tests/
        language: system
        types: [python]
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: python -m mypy app/
        language: system
        types: [python]
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: python -m pytest -q
        language: system
        types: [python]
        pass_filenames: false
